//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVisonIT.AutomatedTellerMachine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionHistory
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int CardId { get; set; }
        public int AccountId { get; set; }
        public int TransactionType { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> TransactionAmount { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Card Card { get; set; }
        public virtual User User { get; set; }
    }
}
